name: Generate xml sitemap

on:
  push:
    branches: [ main ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: List repository files
        run: |
          echo "Listing all files in repository..."
          find . -type f

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://kaveenh.github.io/
          additional-extensions: doc docx ppt pptx xls xlsx

      - name: Check sitemap file
        run: |
          echo "Checking if sitemap.xml exists..."
          ls -la
          if [ -f sitemap.xml ]; then
            echo "sitemap.xml exists. Contents:"
            cat sitemap.xml
          else
            echo "sitemap.xml not found!"
            exit 1
          fi

      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Commit sitemap.xml
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          if git status | grep -q "nothing to commit"; then
            echo "No changes to commit."
          else
            git commit -m "Auto-generate sitemap.xml"
            git push
          fi